### ISSUE TITLE
Transform - FetchError

### ISSUE THREAD

**Issue by FabianCretton** [zazuko/cube-creator#628]
See my project "Fabian_Jahrbuch Wald & Holz 2020_Test 2"
A 85'000 lines csv
For example: https://gitlab.ldbar.ch/pipelines/cube-creator/-/jobs/8861

This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
FetchError: request to https://stardog-int.cluster.ldbar.ch/cube-creator?graph=https%3A%2F%2Fpipelines-integ.lindas.admin.ch%2Fcube-project%2Ffabianjahrbuch-wald-holz-2020test-2-xm3v67vbpkp%2Fcube-data failed, reason: read ECONNRESET
    at ClientRequest.<anonymous> (/app/node_modules/node-fetch/lib/index.js:1461:11)
    at ClientRequest.emit (events.js:327:22)
    at ClientRequest.EventEmitter.emit (domain.js:467:12)
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket.EventEmitter.emit (domain.js:467:12)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)

**Comment by FabianCretton** [comment]
To be noted: 10 minutes before, a transform did run smoothly.
And this run that fails, was done just after, without any change (I juste pressed the "transform" button once again)

**Comment by l00mi** [comment]
https://control.vshn.net/tickets/SBAR-352

**Comment by l00mi** [comment]
More examples: 
* https://gitlab.ldbar.ch/pipelines/cube-creator/-/jobs/9066
* https://gitlab.ldbar.ch/pipelines/cube-creator/-/jobs/9065

VSHN is investigating.

**Comment by l00mi** [comment]
Potential underlying issue in kubernetes: https://github.com/kubernetes/kubernetes/issues/74839
