### ISSUE TITLE
New publication test about the "forestry" cube -> ECONNRESET

### ISSUE THREAD

**Issue by FabianCretton** [zazuko/cube-creator#756]
The cube "transformation" was successful.
The cube "publication" gave a ECONNRESET: https://pipelines-integ.lindas.admin.ch/app/cube-projects/cube-project!!fabforestrynormalized-5ljx6a5axdk/publication

**Comment by FabianCretton** [comment]
On a second run, the error seems different: https://gitlab.ldbar.ch/pipelines/cube-creator/-/jobs/11588
```
Error: Unexpected "<https://environment.ld" on line 778297.
    at N3Lexer._syntaxError (/app/node_modules/n3/lib/N3Lexer.js:466:17)
    at reportSyntaxError (/app/node_modules/n3/lib/N3Lexer.js:394:21)
    at N3Lexer._tokenizeToEnd (/app/node_modules/n3/lib/N3Lexer.js:375:86)
    at /app/node_modules/n3/lib/N3Lexer.js:521:42
    at N3StreamParser._flush (/app/node_modules/n3/lib/N3StreamParser.js:51:7)
    at N3StreamParser.prefinish (/app/node_modules/readable-stream/lib/_stream_transform.js:129:10)
    at N3StreamParser.emit (events.js:376:20)
    at N3StreamParser.emit (domain.js:470:12)
    at prefinish (/app/node_modules/readable-stream/lib/_stream_writable.js:611:14)
    at finishMaybe (/app/node_modules/readable-stream/lib/_stream_writable.js:620:5)
```

**Comment by FabianCretton** [comment]
Today I got the same ECONNRESET error with the cube "Fabian_Jahrbuch Wald & Holz 2020"
https://gitlab.ldbar.ch/pipelines/cube-creator/-/jobs/11703

**Comment by PDumasBAR** [comment]
ça se pourrait bien :)

**Comment by FabianCretton** [comment]
Bonjour @l00mi , avez-vous des nouvelles pour ce problème-ci ?

**Comment by l00mi** [comment]
@tpluscode is this resolved ?

**Comment by tpluscode** [comment]
No. We're waiting for infrastructure changes but so far the core issue has not been identifier

**Comment by l00mi** [comment]
close in favor of #763

**Comment by Rdataflow** [comment]
[publication](https://pipelines-test.lindas.admin.ch/app/cube-projects/cube-project!!ch-bafu-wald-faostat-prod-test002-xxqnddvzz4b/publication) is still failing with ECONNRESET. seems unrelated to the timeout increased by https://control.vshn.net/tickets/SBAR-431

**Comment by Rdataflow** [comment]
is there any isse with VSHN to follow?

**Comment by l00mi** [comment]
Current Issue https://control.vshn.net/tickets/SBAR-480
